
name: Release tagged build

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write
  packages: read

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-tags:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/release-tags.yml@master
    secrets:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
